@startuml Manage Room (GET ALL)

header Room Reservation System Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Room (GET ALL)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:rooms" as routerrooms
participant "<<controllers>>\n:rooms" as controllersrooms
participant "<<model>>\n:Room" as modelroom
database "<<MongoDB>>\n:rooms" as roomsDatabase

client->server ++:req.get('/rooms')
server->routerrooms ++:app.use('/rooms',rooms)
routerrooms -> controllersrooms ++:getRooms()
controllersrooms->modelroom ++:find()
modelroom ->roomsDatabase ++: roomSchema
roomsDatabase --> modelroom --: rooms
controllersrooms <-- modelroom --:rooms
controllersrooms->client --:response

@enduml
